// <auto-generated />
namespace PornCantina.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAvatarImagePathColumnForModelTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAvatarImagePathColumnForModelTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201211112330012_AddAvatarImagePathColumnForModelTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
